runtime: php74

handlers:
# react compiled data
- url: /js
  static_dir: public/js

env_variables:
  APP_KEY: base64:Rb1MVfwFWlVCbCcquR8AgLjVB+ChGewqqxhv6i6W9Qs=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
